version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  face-detect:
    lang: python3-http-debian
    handler: ./face-detect
    image: alexcolladodev2/face-detect:latest
    build_args:
      ADDITIONAL_PACKAGE: "libgl1-mesa-glx libglib2.0-0 curl"


